language: node_js

node_js:
- node

cache:
  directories:
  - node_modules

before_script:
- npm install -g --silent

script:
- gulp build --prod

after_script:
- gulp deploy --user $FTP_USER --password $FTP_PASSWORD
