language: node_js

node_js:
- node

branches:
  only:
  - master

install:
- npm install -g --silent

before_script:
- gulp build --prod

after_script:
- gulp deploy --user $FTP_USER --password $FTP_PASSWORD