# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Gulp.js CI build and deploy via FTP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: 🚚 Get latest source code
      uses: actions/checkout@v2
    - name: 📦 Install npm packages and setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --silent
    - name: 🏗️ Build using gulp.js
      uses: actions/setup-node@v2
    - run: npm run build
    - name: 📂 Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftp.amiroff.me
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/
        server-dir: amiroffme/
        
